"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var movie_1 = require("./movie");
var profesional_1 = require("./profesional");
var readlineSync = require('readline-sync');
var name = readlineSync.question("ingrese su nombre:  ");
var edad = readlineSync.questionInt("ingrese su edad:  ");
var peso = readlineSync.questionInt("ingrese su peso  ");
var altura = readlineSync.questionInt("ingrese su altura:  ");
var estaRetirado = readlineSync.keyInYN("esta usted retirado:  ");
var nacionalidad = readlineSync.question("cual es su nacionalidad:  ");
var Oscars = readlineSync.questionInt("tiene algun Oscar:  ");
var profesion = readlineSync.question("cual es su profesion:  ");
var profesional = new profesional_1.Profesional(name, edad, peso, altura, estaRetirado, nacionalidad, Oscars, profesion);
console.log(profesional);
var pelitest = new movie_1.Movie("vida eterna", 1996, "japonesa", "drama");
pelitest.actors = [profesional];
console.log(pelitest.actors);
console.log(pelitest);
